// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJyply-LNuhtSbNqzXAqGi5MNmVfOnDTQ',
    appId: '1:285478656335:web:28ea188caa52d8c7980d3a',
    messagingSenderId: '285478656335',
    projectId: 'whatsapp24',
    authDomain: 'whatsapp24.firebaseapp.com',
    storageBucket: 'whatsapp24.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3EhnhvnReRBHpIV4Tl29wFu3yTO7nd18',
    appId: '1:285478656335:android:76946d36d96a207c980d3a',
    messagingSenderId: '285478656335',
    projectId: 'whatsapp24',
    storageBucket: 'whatsapp24.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeCp19SauP7bCDnfOiozFEcJa9ZV3VQXg',
    appId: '1:285478656335:ios:93f7bc402e20f1b2980d3a',
    messagingSenderId: '285478656335',
    projectId: 'whatsapp24',
    storageBucket: 'whatsapp24.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeCp19SauP7bCDnfOiozFEcJa9ZV3VQXg',
    appId: '1:285478656335:ios:93f7bc402e20f1b2980d3a',
    messagingSenderId: '285478656335',
    projectId: 'whatsapp24',
    storageBucket: 'whatsapp24.firebasestorage.app',
    iosBundleId: 'com.example.whatsappClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDJyply-LNuhtSbNqzXAqGi5MNmVfOnDTQ',
    appId: '1:285478656335:web:2b5e90f9196f1f7e980d3a',
    messagingSenderId: '285478656335',
    projectId: 'whatsapp24',
    authDomain: 'whatsapp24.firebaseapp.com',
    storageBucket: 'whatsapp24.firebasestorage.app',
  );
}
